services:
  chrome:
    image: browserless/chrome:latest
    ports:
      - "9222:3000"  # browserless uses port 3000 internally
    environment:
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=0
      - ENABLE_DEBUGGER=true
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - HEALTH=true
      - DEFAULT_LAUNCH_ARGS=["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--disable-gpu"]
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  chrome-data:
